lingo/urls.py
# lingo - basket and payment system
# Copyright (C) 2015  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url, include

from combo.urls_utils import decorated_includes, manager_required

from .views import (RegiesApiView, AddBasketItemApiView, PayView, CallbackView,
                    ReturnView, ItemDownloadView, ItemView)
from .manager_views import (RegieListView, RegieCreateView, RegieUpdateView,
        RegieDeleteView, TransactionListView, ManagerHomeView)

lingo_manager_urls = patterns('lingo.manager_views',
    url('^$', ManagerHomeView.as_view(), name='lingo-manager-homepage'),
    url('^transactions/$', TransactionListView.as_view(), name='lingo-manager-transactions-list'),
    url('^regies/$', RegieListView.as_view(), name='lingo-manager-regie-list'),
    url('^regies/add/$', RegieCreateView.as_view(), name='lingo-manager-regie-add'),
    url('^regies/(?P<pk>\w+)/edit$', RegieUpdateView.as_view(),
        name='lingo-manager-regie-edit'),
    url('^regies/(?P<pk>\w+)/delete$', RegieDeleteView.as_view(),
        name='lingo-manager-regie-delete'),
)

urlpatterns = patterns('',
    url('^api/lingo/regies$', RegiesApiView.as_view(), name='api-regies'),
    url('^api/lingo/add-basket-item$', AddBasketItemApiView.as_view(),
        name='api-add-basket-item'),
    url(r'^lingo/pay$', PayView.as_view(), name='lingo-pay'),
    url(r'^lingo/callback/(?P<regie_pk>\w+)/$', CallbackView.as_view(), name='lingo-callback'),
    url(r'^lingo/return/(?P<regie_pk>\w+)/$', ReturnView.as_view(), name='lingo-return'),
    url(r'^manage/lingo/', decorated_includes(manager_required,
        include(lingo_manager_urls))),
    url(r'^lingo/item/(?P<regie_id>[\w,-]+)/(?P<item_id>[\w,-]+)/pdf$',
        ItemDownloadView.as_view(), name='download-item-pdf'),
    url(r'^lingo/item/(?P<regie_id>[\w,-]+)/(?P<item_id>[\w,-]+)/$',
        ItemView.as_view(), name='view-item'),
)

lingo/models.py
# lingo - basket and payment system
# Copyright (C) 2015  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import datetime
import json
import requests
import urllib
from dateutil import parser
from decimal import Decimal

import eopayment
from jsonfield import JSONField

from django import template
from django.conf import settings
from django.db import models
from django.forms import models as model_forms, Select
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.exceptions import PermissionDenied

from ckeditor.fields import RichTextField

from combo.data.models import CellBase
from combo.data.library import register_cell_class
from combo.utils import NothingInCacheException, sign_url


SERVICES = [
    (eopayment.DUMMY, _('Dummy (for tests)')),
    (eopayment.SYSTEMPAY, 'systempay (Banque Populaire)'),
    (eopayment.SIPS, 'SIPS'),
    (eopayment.SPPLUS, _('SP+ (Caisse d\'epargne)')),
    (eopayment.OGONE, _('Ingenico (formerly Ogone)')),
    (eopayment.PAYBOX, _('Paybox')),
    (eopayment.PAYZEN, _('PayZen')),
]


def build_remote_item(data, regie):
    return RemoteItem(id=data.get('id'), regie=regie,
                      creation_date=data['created'],
                      payment_limit_date=data['pay_limit_date'],
                      display_id=data['display_id'],
                      total_amount=data.get('total_amount'),
                      amount=data.get('amount'),
                      subject=data.get('label'),
                      has_pdf=data.get('has_pdf'),
                      online_payment=data.get('online_payment'))


class Regie(models.Model):
    label = models.CharField(verbose_name=_('Label'), max_length=64)
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name=_('Description'))
    service = models.CharField(verbose_name=_('Payment Service'),
            max_length=64, choices=SERVICES)
    service_options = JSONField(blank=True,
            verbose_name=_('Payment Service Options'))
    webservice_url = models.URLField(_('Webservice URL to retrieve remote items'),
                        blank=True)
    payment_min_amount = models.DecimalField(_('Minimal payment amount'),
                            max_digits=7, decimal_places=2, default=0)

    def is_remote(self):
        return self.webservice_url != ''

    class Meta:
        verbose_name = _('Regie')

    def natural_key(self):
        return (self.slug,)

    def __unicode__(self):
        return self.label

    def get_past_items(self, context):
        """
        returns past items
        """
        return self.get_items(context, past=True)


    def get_items(self, context, past=False):
        """
        returns current or past items
        """
        if not self.is_remote():
            payed = not past
            return self.basketitem_set.filter(payment_date__isnull=payed,
                                              user=context.get('user'))
        if context.get('user'):
            if context.get('request') and hasattr(context['request'], 'session') and \
               context['request'].session.get('mellon_session'):
                mellon = context.get('request').session['mellon_session']
                url = self.webservice_url + '/invoices/'
                if past:
                    url += 'history'
                items = requests.get(self.signed_url(context['request'], url,
                            NameID=mellon['name_id_content'])).json()
                if items.get('data'):
                    return [build_remote_item(item, self) for item in items.get('data')]
                return []
        return []

    def download_item(self, request, item_id):
        """
        downloads item's file
        """
        if self.is_remote():
            if hasattr(request, 'session') and request.session.get('mellon_session'):
                mellon = request.session.get('mellon_session')
                url = self.webservice_url + '/invoice/%s/pdf' % item_id
                return requests.get(self.signed_url(request, url,
                                    NameID=mellon['name_id_content']))
            raise PermissionDenied

    def get_item(self, request, item):
        if not self.is_remote():
            return self.basketitem_set.get(pk=item)

        if hasattr(request, 'session') and request.session.get('mellon_session'):
            mellon = request.session.get('mellon_session')
            url = self.webservice_url + '/invoice/%s/' % item
            item = requests.get(self.signed_url(request, url,
                        NameID=mellon['name_id_content'])).json()
            return build_remote_item(item.get('data'), self)
        return {}

    def pay_item(self, request, item, transaction_id, transaction_date):
        url = self.webservice_url + '/invoice/pay/'
        data = {'invoice_id': item, 'transaction_id': transaction_id,
                'transaction_date': transaction_date.strftime('%Y-%m-%dT%H:%M:%S')}
        headers = {'content-type': 'application/json'}
        return requests.post(self.signed_url(request, url),
                             data=json.dumps(data), headers=headers).json()

    def as_api_dict(self):
        return {'slug': self.slug,
                'label': self.label,
                'description': self.description}

    def signed_url(self, request, url, **params):
        orig = request.get_host()
        url += '?orig=' + orig +'&' + urllib.urlencode(params)
        signature_key = settings.LINGO_SIGNATURE_KEY
        return sign_url(url, key=signature_key)


class BasketItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    regie = models.ForeignKey(Regie)
    subject = models.CharField(verbose_name=_('Subject'), max_length=64)
    source_url = models.URLField(_('Source URL'))
    details = models.TextField(verbose_name=_('Details'), blank=True)
    amount = models.DecimalField(verbose_name=_('Amount'),
            decimal_places=2, max_digits=8)
    creation_date = models.DateTimeField(auto_now_add=True)
    cancellation_date = models.DateTimeField(null=True)
    payment_date = models.DateTimeField(null=True)
    notification_date = models.DateTimeField(null=True)

    def notify(self):
        # TODO: sign with real values
        url = self.source_url + 'jump/trigger/paid?email=trigger@localhost&orig=combo'
        url = sign_url(url, key='xxx')
        message = {'result': 'ok'}
        r = requests.post(url, data=json.dumps(message), timeout=3)
        self.notification_date = timezone.now()
        self.save()


class RemoteItem(object):
    def __init__(self, id, regie, creation_date, payment_limit_date,
                 total_amount, amount, display_id, subject, has_pdf,
                 online_payment):
        self.id = id
        self.regie = regie
        self.creation_date = parser.parse(creation_date)
        self.payment_limit_date = parser.parse(payment_limit_date)
        self.total_amount = Decimal(total_amount)
        self.amount = Decimal(amount)
        self.display_id = display_id
        self.subject = subject
        self.has_pdf = has_pdf
        self.online_payment = online_payment


class Transaction(models.Model):
    regie = models.ForeignKey(Regie, null=True)
    items = models.ManyToManyField(BasketItem, blank=True)
    remote_items = models.CharField(max_length=512)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(null=True)
    bank_data = JSONField(blank=True)
    order_id = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    status = models.IntegerField(null=True)
    amount = models.DecimalField(default=0, max_digits=7, decimal_places=2)

    def is_remote(self):
        return self.remote_items != ''

    def is_paid(self):
        return self.status == eopayment.PAID

    def get_status_label(self):
        return {
            0: _('Running'),
            eopayment.PAID: _('Paid'),
            eopayment.CANCELLED: _('Cancelled'),
        }.get(self.status) or _('Unknown')

@register_cell_class
class LingoBasketCell(CellBase):

    class Meta:
        verbose_name = _('Basket')

    @classmethod
    def is_enabled(cls):
        return Regie.objects.count() > 0

    def is_relevant(self, context):
        if not (getattr(context['request'], 'user', None) and context['request'].user.is_authenticated()):
            return False
        items = BasketItem.objects.filter(
                user=context['request'].user, payment_date__isnull=True
                ).exclude(cancellation_date__isnull=False)
        return len(items) > 0

    def render(self, context):
        basket_template = template.loader.get_template('lingo/combo/basket.html')
        context['items'] = BasketItem.objects.filter(
                user=context['request'].user, payment_date__isnull=True
                ).exclude(cancellation_date__isnull=False)
        context['total'] = sum([x.amount for x in context['items']])
        return basket_template.render(context)


@register_cell_class
class LingoRecentTransactionsCell(CellBase):

    class Meta:
        verbose_name = _('Recent Transactions')

    @classmethod
    def is_enabled(cls):
        return Regie.objects.count() > 0

    def is_relevant(self, context):

lingo/templates/lingo/manager_base.html
{% extends "combo/manager_base.html" %}
{% load i18n %}

{% block appbar %}
<h2>{% trans 'Online Payment' %}</h2>
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
<a href="{% url 'lingo-manager-homepage' %}">{% trans 'Online Payment' %}</a>
{% endblock %}

lingo/templates/lingo/manager_home.html
{% extends "lingo/manager_base.html" %}
{% load i18n %}

{% block content %}
<ul class="apps">
 <li><a class="button" href="{% url 'lingo-manager-transactions-list' %}">{% trans 'Transactions' %}</a></li>
 <li><a class="button" href="{% url 'lingo-manager-regie-list' %}">{% trans 'Regies' %}</a></li>
</ul>
{% endblock %}

lingo/templates/lingo/payment_form.html
{% load i18n %}
<html>
<head>
</head>
<body onload="document.forms[0].submit()">
<p>
{% trans "Please wait while your browser is being redirected to the payment website..." %}
</p>
<form action="{{ form.url }}" method="{{ form.method }}" style="display: none">
  {% for field in form.fields %}
  <input type="{{ field.type }}" name="{{ field.name }}" value="{{ field.value }}"/>
  {% endfor %}
  <input type="submit">
</form>
</body>
</html>

lingo/templates/lingo/regie_confirm_delete.html
{% extends "combo/manager_base.html" %}
{% load i18n %}

{% block appbar %}
<h2>{{ view.model.get_verbose_name }}</h2>
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {% blocktrans %}Are you sure you want to delete this?{% endblocktrans %}
  <div class="buttons">
    <button>{% trans 'Confirm Deletion' %}</button>
    <a class="cancel" href="{% url 'lingo-manager-homepage' %}">{% trans 'Cancel' %}</a>
  </div>
</form>
{% endblock %}

lingo/templates/lingo/regie_form.html
{% extends "lingo/regie_list.html" %}
{% load i18n %}

{% block appbar %}
{% if object.id %}
<h2>{% trans "Edit Regie" %}</h2>
{% else %}
<h2>{% trans "New Regie" %}</h2>
{% endif %}
{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="buttons">
    <button>{% trans "Save" %}</button>
    <a class="cancel" href="{% url 'lingo-manager-homepage' %}">{% trans 'Cancel' %}</a>
    {% if object.id %}
    <a class="delete" rel="popup" href="{% url 'lingo-manager-regie-delete' pk=object.id %}">{% trans 'Delete' %}</a>
    {% endif %}
  </div>
</form>
{% endblock %}

lingo/templates/lingo/regie_list.html
{% extends "lingo/manager_base.html" %}
{% load i18n %}

{% block appbar %}
<h2>{% trans 'Regies' %}</h2>
<a rel="popup" href="{% url 'lingo-manager-regie-add' %}">{% trans 'New' %}</a>
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
<a href="{% url 'lingo-manager-regie-list' %}">{% trans 'Regies' %}</a>
{% endblock %}

{% block content %}

{% if object_list %}
<div class="objects-list">
 {% for regie in object_list %}
 <div>
 <a href="{% url 'lingo-manager-regie-edit' pk=regie.id %}">{{ regie.label }} <span>({{regie.service}})</span></a>
 </div>
 {% endfor %}
</div>
{% else %}
<div class="big-msg-info">
  {% blocktrans %}
  This site doesn't have any regie yet. Click on the "New" button in the top
  right of the page to add a first one.
  {% endblocktrans %}
</div>
{% endif %}

{% endblock %}

lingo/templates/lingo/transaction_list.html
{% extends "lingo/manager_base.html" %}
{% load i18n %}

{% block appbar %}
<h2>{% trans 'Transactions' %}</h2>
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
<a href="{% url 'lingo-manager-transactions-list' %}">{% trans 'Transactions' %}</a>
{% endblock %}

{% block content %}

{% if object_list %}
<table class="main">
<thead>
  <tr>
   <th>{% trans 'Transaction Identifier' %}</th>
   <th>{% trans 'Date' %}</th>
   <th>{% trans 'User' %}</th>
   <th>{% trans 'Amount' %}</th>
   <th colspan="2">{% trans 'Items' %}</th>
  </tr>
</thead>
<tbody>
{% for object in object_list %}
<tr>
 <td rowspan="{{object.items.all.count}}">{{object.order_id}}</td>
 <td rowspan="{{object.items.all.count}}">{{object.start_date}}</td>
 <td rowspan="{{object.items.all.count}}">{{object.user.first_name}} {{object.user.last_name}}</td>
 <td rowspan="{{object.items.all.count}}">{{object.amount}} €</td>
 {% for item in object.items.all %}
 {% if not forloop.first %}<tr>{% endif %}
  <td style="font-size: smaller">{{item.subject}}</td> <td style="font-size: smaller" class="price">{{item.amount}} €</td></tr>
  {% endfor %}
  {% if not object.items.all %}</tr>{% endif %}
 {% endfor %}
</tbody>
</table>

{% if is_paginated %}
<p class="paginator">
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;</a>
  {% else %}
    <span>&lt;&lt;</span>
  {% endif %}

  &nbsp;
  <span class="current">
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
  </span>
  &nbsp;

  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&gt;&gt;</a>
  {% else %}
    <span>&gt;&gt;</span>
  {% endif %}
</div>
{% endif %}


</div>
{% else %}
<div class="big-msg-info">
  {% blocktrans %}
  This site doesn't have any transaction yet.
  {% endblocktrans %}
</div>
{% endif %}

{% endblock %}